name: Build everything

on:  
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  job_build_win:
    name: Build for Windows
    runs-on: ubuntu-latest
    container: 
      image: defter/jamtaba-${{ matrix.os }}:v5.15.7
    strategy:
      matrix:
        os:
          - win32
          - win64
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Build everything
        shell: bash
        env:
          JAMTABA_VERSION: 1.0.0
        run: |
          cd ./PROJECTS
          qmake . CONFIG+=release
          make -j$(nproc)

  job_build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container: 
      image: defter/jamtaba-${{ matrix.os }}:v5.15.7
    strategy:
      matrix:
        os:
          - linux
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Build everything
        shell: bash
        env:
          JAMTABA_VERSION: 1.0.0
        run: |
          cd ./PROJECTS
          qmake . CONFIG+=release
          make -j$(nproc)
