name: Build/Upload everything for Windows 64 bit (x64)

on: workflow_dispatch

jobs:
  build_all:
    runs-on: ubuntu-latest
    container: 
      image: defter/jamtaba-win64:v5.15.7

    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          cd ./PROJECTS
          qmake . CONFIG+=release
          make -j$(nproc)

             - name: Create applications archive
        shell: bash
        run: |
          cd ./PROJECTS/Standalone/release
          zip jamtaba-win64-${{ env.JAMTABA_VERSION }}.zip Jamtaba2.exe VstScanner.exe
          mv jamtaba.win64-${{ env.JAMTABA_VERSION }}.zip  ../../../

      - name: Create plugin archive
        shell: bash
        run: |
          cd ./PROJECTS/VstPlugin/release
          zip jamtaba-win64-VST-${{ env.JAMTABA_VERSION }}.zip JamtabaVST2.dll
          mv jamtaba-win64-VST.${{ env.JAMTABA_VERSION }}.zip ../../../

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jamtaba-win64-${{ env.JAMTABA_VERSION }}
          path: jamtaba-win64-${{ env.JAMTABA_VERSION }}.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jamtaba-win64-VST-${{ env.JAMTABA_VERSION }}
          path: jamtaba-win64-VST-${{ env.JAMTABA_VERSION }}.zip


